### ISSUE TITLE
Decoding issue

### ISSUE THREAD

**Issue by JodusNodus** [cozmo/jsQR#11]
When scanning a QR code with the following value:
`YAZBNS5-T7TTTOJ-G4UZATU-BAF2SOG-LMXMDH2-Z5PDXF6-27SUVQ7-NS6FGA5`
It returns this:
`undefinedAundefinedBundefinedSundefined-undefined7undefinedTundefinedOundefined-undefined4undefinedZundefinedTundefined-undefinedAundefined2undefinedOundefined-undefinedMundefinedMundefinedHundefined-undefined5undefinedDundefinedFundefined-undefined7undefinedUundefinedQundefined-undefinedSundefinedFundefinedA5`

**Comment by jefff** [comment]
Thanks for reporting this issue. I believe I've narrowed down the problem and have a fix in master. I should be able to deploy it to npm in the next few days.

**Comment by JodusNodus** [comment]
Great, Thank you for the quick fix. 👍 
I will test it out when it is released and hopefully close the issue.

**Comment by cozmo** [comment]
@JodusNodus Just wanted to provide an update here - This was fixed (I believe) in https://github.com/cozmo/jsQR/pull/12/commits/beef8b9ad0feb925c2d63d9006ea12c9d1ef1b4f, which was on master since that PR but just got published to npm as version `2.0.1` tonight. 

Sorry for the delay in publishing, that was our bad :(

I'm going to close the issue as fixed, feel free to re-open if you find this is still an issue.
