### ISSUE TITLE
jsQR taking screenshot instead of video streaming, Unable to scan QR Code

### ISSUE THREAD

**Issue by prsuman82** [cozmo/jsQR#110]
Hi, 
I have used the demo code. It is working fine in the demo site, but same code is not working when i imported into our application. It is only taking screenshot when i initiate the code.  

Please let us know how to resolve this case

**Comment by cozmo** [comment]
As mentioned in the [README](https://github.com/cozmo/jsQR#a-note-on-webcams) jsQR is designed to have no webcam specific implementation details. Rather the API is designed to take in image data and output any QR codes found within. Handling reading image data from the webcam and passing it to jsQR is the responsibility of the consumer, and as such I can't provide much help here.

The demo site was meant to be a simple demo, so doesn't do any advanced image/video capture. I'm not sure exactly what you mean by "taking a screenshot" but if it's just playing one frame it's possible there's an error being thrown? I'd ensure no errors are in the console and otherwise start adding debugging statements or such to figure out what is causing the hang. 

Closing this issue since it doesn't relate to a jsQR issue specifically, but feel free to comment/re-open if you disagree or have additional questions.
