### ISSUE TITLE
Can i decode this images?

### ISSUE THREAD

**Issue by ternaryCat** [cozmo/jsQR#125]
i tryed this demo https://codesandbox.io/s/pwoywz6n5x

it can't decode qr with custom background/logo

Is there way decode images ?
![image3](https://user-images.githubusercontent.com/24289268/54412078-7c27ca80-4702-11e9-9029-6bb153cdde4b.png)
![image4](https://user-images.githubusercontent.com/24289268/54412080-7c27ca80-4702-11e9-82ee-b34f76f517a1.png)

**Comment by atkulp** [comment]
Any QR code scanner is going to need enough contrast between black and white squares.  This one has a beer glass in front if it though.  I can't imagine any reader liking it.

**Comment by ternaryCat** [comment]
jsQR was able to scan this image, the problem was that he does not perceive the image if there are transparent pixels on it

**Comment by cozmo** [comment]
Yea we decided not to support transparent pngs, since transparent pixels have undefined behavior. For example for people with inverted QR codes (white modules on black backgrounds), assuming transparent pixels were white would cause the QR codes not to scan. 

If you know you can safely assume transparent pixels are a certain color you should be able to easily process the input data to encode that assumption. If you think we should support transparent images please open an issue (or better, a PR) and I'm happy to discuss.
