### ISSUE TITLE
I cannot decode image of front mobile

### ISSUE THREAD

**Issue by jonathasfujii** [cozmo/jsQR#126]
I cannot decode image of front mobile.

**Comment by atkulp** [comment]
Can you provide any more details?  Not a developer of it, but I've tested it with great results.  You need a camera with good enough quality of course though it's pretty forgiving.

**Comment by jonathasfujii** [comment]
The library works very well with the rear camera of the phone, but when
using the front camera can not recognize the qr-code, the equipment used is
a Smasung S7.

Atenciosamente,

Jonathas Fujii


Em qui, 21 de mar de 2019 às 02:00, Arian Kulp <notifications@github.com>
escreveu:

**Comment by atkulp** [comment]
As I understand it the camera makes no difference.  The library is just looking at an image, in your case, the current frame of the video stream.  Perhaps your cameras have different resolutions and what you're passing isn't lined up right.  Since the library doesn't do the actual frame capture, make sure you have a preview window so you can see that it's capturing properly, and make sure your code isn't make any assumptions about the canvas image.

**Comment by cozmo** [comment]
@atkulp is correct in that this library just processes image data and as such any issues should be results of aspects of the image, not the device that captured it. As such going to close this issue but pleas feel free to comment or re-open with specific failure cases that should succeed.
