### ISSUE TITLE
jsQR not work in iframe when run on ipad

### ISSUE THREAD

**Issue by tiepvb** [cozmo/jsQR#147]
add code in iframe with allow
```
<iframe allow="accelerometer *; ambient-light-sensor *; autoplay *; camera *; encrypted-media *; fullscreen *; geolocation *; gyroscope *; magnetometer *; microphone *; midi *; payment *; picture-in-picture *; speaker *; usb *; vibrate *; vr *">
```
on pc it's ok but ipad can't detect camera
Pls help
thanks!

**Comment by cozmo** [comment]
Since `jsQR` is just a function, it will work wherever javascript can run (iframe or not). What it sounds like the issue you're describing is the _webcam_ not working in the iframe. As I mention [here](https://github.com/cozmo/jsQR#a-note-on-webcams) I'm not a webcam expert by any stretch, and as such can't really help you debug non jsQR issues unfortunately. That said it seems like there are some [caveats](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Privacy_and_security) around [accessing webcam data in iframes](https://stackoverflow.com/questions/53483975/navigator-mediadevices-getusermedia-not-working-on-ios-12-safari). 

If you can get the video working in an iframe without jsQR, and jsQR somehow breaks, then please let me know, but if you're just having trouble getting the _video_ to work I'd suggest asking on stackoverflow or somewhere that will be able to help you more with webcam specific code. 

Closing this issue for now but if you have a bug with jsQR please comment/re-open!
