### ISSUE TITLE
JSQR from url

### ISSUE THREAD

**Issue by slidenerd** [cozmo/jsQR#16]
Hi cozmo , thank you for the fantastic jsqr port, i see that the 1st parameter is a 1d data array for image data but there are often cases like mine where we need to read image from a url, would it be possible for you to enhance the library to read qr data even from a URL like [this ](https://www.moo.com/images/qr-code/kitten-qr.jpg)

Thanks for your work in advance

**Comment by cozmo** [comment]
This library works on the backend so you can use normal node libraries to download the data from the url. A (working) example of this would be something like

```javascript
request = require("request"); // https://github.com/request/request
png = new (require('pngjs').PNG)(); // https://www.npmjs.com/package/pngjs
jsQR = require("jsqr");

request({
  uri: "https://www.moo.com/images/qr-code/kitten-qr.jpg",
  encoding: null // Force null encoding to get data as a buffer
}, function(err, resp, body) { // Download the image
  if(err) {
    console.error(err);
    process.exit(1);
  }
  png.parse(body, function(err, decodedPng) { // Parse the png
    if(err) {
      console.error(err);
      process.exit(1);
    }
    // Use jsQR to decode it
    console.log(jsQR.decodeQRFromImage(decodedPng.data, decodedPng.width, decodedPng.height))
  });
});
```

When I run this locally it produces `http://www.moo.com/images/qr-code/hidden-kittens.jpg`. 

One thing to note is even though this image had the `jpg` extension, it's actually a png. If you need to support arbitrary urls I'd use something like https://www.npmjs.com/package/image-type to detect the image type correctly. 

I'm going to close this issue since the above solution works as far as I know, but if I misunderstood or if you have more questions feel free to re-open.

**Comment by CallMeXYZ** [comment]
example for latest pngjs and jsqr
```
const nodeFetch = require('node-fetch')
const pngjs = require('pngjs')
const jsqr = require("jsqr");
const getCodeFromQrCodeImageUrl = (url) => {
    return nodeFetch(url).then(res => res.buffer()).then(buff => {
        const image = pngjs.PNG.sync.read(buff)
        const data = new Uint8Array(image.data)
        return jsqr(data, image.width, image.height).data
    })
}
```
