### ISSUE TITLE
Function to stop using camera

### ISSUE THREAD

**Issue by ro78** [cozmo/jsQR#175]
Hello,

I use jsQR inside a Bootstrap's modal window opened through a button.
When I close the modal, the camera is still in use.
There is no "video" object so I can't use video.pause() or similar.

Any idea?

Best regards,
Romain

**Comment by cozmo** [comment]
I found this issue (https://github.com/cozmo/jsQR/issues/17), which seems to have an idea, but like I said there, nothing about jsQR makes any assumptions about _where_ image data is coming from, so I can't be of much help here, since stopping the camera is completely dependent on how you're consuming the camera.
