### ISSUE TITLE
Unable to scan small sized qr codes

### ISSUE THREAD

**Issue by sagar7993** [cozmo/jsQR#56]
![img_20180523_194441](https://user-images.githubusercontent.com/7478918/40430118-02eb8fea-5ec2-11e8-8e6b-670883fe7db5.jpg)

Hi, i'm unable to scan smaller images. The library works perfectly only with large images. I've attached a sample image for your reference. Have tried all kinds of different angles, zoom levels, lighting etc, nothing worked.

**Comment by cozmo** [comment]
@sagar7993 Do you have a scanner that is able to scan this image? I'm not able to get it to scan with https://zxing.org/w/decode.jspx which is in many cases the gold standard implementation. 

I'd love to support codes with this much information density but it seems like we're starting to run up against limits of the camera/error correction. My gut says there may not be enough fidelity to make this possible.

**Comment by cozmo** [comment]
Closing due to lack of response. @sagar7993 please re-open if you've been able to get this image to scan with other scanners (Like https://zxing.org/w/decode.jspx). If this is somewhere that we're unable to scan but other scanners can I'd consider that a bug. Otherwise it may just be that image is too low resolution to extract enough info from?
