### ISSUE TITLE
Wont scan if canvas is small.

### ISSUE THREAD

**Issue by MickyDNet** [cozmo/jsQR#66]
I've had to create a large canvas and a small canvas because it will not scan the qr code if the main canvas is small. This is making my page extremely slow :/

**Comment by cozmo** [comment]
As mentioned [here](https://github.com/cozmo/jsQR#a-note-on-webcams) jsQR is built to be agnostic around where the image data comes from. It has no specific support for webcams vs just providing images directly etc. All it needs is raw image data that may contain a QR code. If you pass it an image too small to read (whether it be from a webcam or otherwise) it won't be able to find a code within. 

I am not a webcam expert and I don't your constraints so unfortunately I may not be able to provide much help here. One idea that might be worth trying is shrinking your canvas with CSS so that the underlying canvas is full resolution, but visually it's shrunk to fit wherever you need it. I tried this real quick with our example code and it seems to work quite well.
