### ISSUE TITLE
How to toggle camera on and off conditionally?

### ISSUE THREAD

**Issue by hoangnguyen208** [cozmo/jsQR#87]
Hi, if I don't want the camera always shows, how can I toggle it off? Specifically, in my case, I have a form and decoding QR code is one of result I have to submit. QR code is the last field in the form I have to submit, so I want user to focus to fill all of the fields then toggle on the camera to get QR code before submitting the form. How can I achieve this feature?

**Comment by chidonna** [comment]
What you can do is open the web cam using a button and an event listener.

**Comment by cozmo** [comment]
So this would fall under our [note on webcams](https://github.com/cozmo/jsQR#a-note-on-webcams) - Specifically, jsQR is not designed specifically to work with a specific webcam setup, rather it's designed to work independently so that you can adapt to whatever your situation is. 

That said, generally it comes down to when you read data from the webcam and send it to jsQR. For example in our [demo](
https://cozmo.github.io/jsQR/) we [immediately ask for camera permissions and start capturing frames with the `tick` function](https://github.com/cozmo/jsQR/blob/master/docs/index.html#L84-L116). it seems like in your case you'd want to do this once the user gets to that part of the form? This is what @chidonna is describing I believe. 

If you have more questions about this I'd check out the resources mentioned in the note on webcams. I'm going to close this issue but if you believe that to be in error or have more questions feel free to re-open.
